### ISSUE TITLE
Suggestion to write out custom data into pngInfo

### ISSUE THREAD

**Issue by jdietzChina** [light-and-ray/sd-webui-hardware-info-in-metadata#2]
Hey Andray,

Love this tool, incredibly handy!

I have a couple suggestions.  First is to just have a way to write some text into a "description" or "notes" valueName to the pngInfo when it runs your tool.

Second, and a little harder would be to have a way to add your own custom valueNames into the pngInfo.  Like I could add the valueName: "character name" and then enter the character's name.  Or "project name" and put in a project name.  So basically some functionality to add valueNames and their value that get added to the pngInfo.

Thanks again, really find this useful!

**Comment by light-and-ray** [comment]
Okay, maybe I'll add note field into options, and you will be able to edit it in quick settings

**Comment by light-and-ray** [comment]
Do you want it overrides "Hardware info" text, or in addition to it?

**Comment by jdietzChina** [comment]
> Do you want it overrides "Hardware info" text, or in addition to it?

In addition to would be perfect!

**Comment by light-and-ray** [comment]
Done!
![](https://github.com/light-and-ray/sd-webui-hardware-info-in-metadata/raw/master/img/img2.jpg)
